version: "3.9"
services:
  # mysql:
  #   image: mysql:8.0
  #   restart: always
  #   volumes:
  #     - ./docker-volume/mysql:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_USER=user
  #     - MYSQL_DATABASE=db
  #   ports:
  #     - "3306:3306"
  #   expose:
  #     - "3306"

  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./docker-volume/postgresql:/var/lib/postgresql/data
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    expose:
      - "5432"
